#!/bin/sh
# Start/stop the mb daemon.
#
### BEGIN INIT INFO
# Provides:	         spawn-fcgi
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the mb with fcgi
# Description:       starts mb using start-stop-daemon
### END INIT INFO

. /lib/lsb/init-functions

FCGI="/usr/bin/spawn-fcgi"
MB="/usr/local/bin/mb"
CONFD="/etc/mb/conf.d"
USER="www-data"

test -x $FCGI || exit 0
test -x $MB || exit 0
	

var_upd() {
	SOCK="/tmp/mb_$ID-fcgi.sock"
	PID="/var/run/mb_$ID.pid"
}

do_start() {
	cd $CONFD
	for ID in *; do
		var_upd
		if [ ! `echo $ID | sed -n '/^[[:alnum:]]\{,32\}$/p'` ];
		then log_failure_msg "Incorrect config filename \"$CONFD/$ID\""
		else
			log_daemon_msg "Starting mb" "$ID"
			start-stop-daemon --start --quiet -p $PID --exec $MB --test &&
			start-stop-daemon --start --exec $FCGI -- -P $PID -u $USER -g $USER -s $SOCK -- $MB -c $CONFD/$ID > /dev/null
			RETVAL=$?
			[ $RETVAL -lt 2 ] && log_end_msg 0 || log_end_msg 1
		fi
	done
}

do_stop() {
	cd $CONFD
	for ID in *; do
		var_upd
		if [ ! `echo $ID | sed -n '/^[[:alnum:]]\{,32\}$/p'` ];
		then log_failure_msg "Incorrect config filename \"$CONFD/$ID\""
		else
			log_daemon_msg "Stopping mb" "$ID"
			start-stop-daemon --stop --quiet --pidfile $PID
			RETVAL=$?
			[ $RETVAL -eq 0 ] && [ -e "$PID" ] && rm -f $PID
			[ $RETVAL -lt 2 ] && log_end_msg 0 || log_end_msg 1
		fi
	done
}

status() {
	cd $CONFD
	for ID in *; do
		var_upd
		if [ ! `echo $ID | sed -n '/^[[:alnum:]]\{,32\}$/p'` ];
		then log_failure_msg "Incorrect config filename \"$CONFD/$ID\""
		else status_of_proc -p $PID $MB "Process mb: $ID"
		fi
	done
}

RETVAL=0
case "$1" in
	start)
		do_start
		RETVAL=$?
	;;
	stop)
		do_stop
		RETVAL=$?
	;;
	restart)
		do_stop
		do_start
		RETVAL=$?
	;;
	status)
		status
		RETVAL=$?
	;;
	*)
		echo "Usage: mb-daemon {start|stop|status|restart}"
		exit 1
	;;
esac
exit $RETVAL
