#!/bin/bash
START="/usr/bin/spawn-fcgi -P /var/log/nginx/mb.pid -u www-data -g www-data -s /tmp/mb-fcgi.sock -- /usr/local/bin/mb -c /usr/local/share/mb/config.js"
STOP="killall -9 /usr/local/bin/mb"
RETVAL=0
case "$1" in
start)
$START
RETVAL=$?
;;
stop)
$STOP
RETVAL=$?
;;
restart)
$STOP
$START
RETVAL=$?
;;
*)
echo "Usage: mb-spawn-daemon {start|stop|restart}"
exit 1
;;
esac
exit $RETVAL
